name: spotify_insights
description: "Spotify playlist analytics and insights"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  fl_chart: ^1.1.1
  flutter_dotenv: ^6.0.0
  http: ^1.2.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  path: ^1.9.0
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.1.0
  json_serializable: ^6.8.0
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
